import ReduxProvider from "@/redux/ReduxProvider";
import type { Metadata } from "next";
import { Jost } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const outfit = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={outfit.className}>
          <div>
            <Toaster />
          </div>
          {children}
        </body>
      </ReduxProvider>
    </html>
  );
}
