import ReduxProvider from "@/redux/ReduxProvider";
import type { Metadata } from "next";
import { Jost } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import ToastProvider from "./providers/toast.provider";
const outfit = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <ToastContainer /> */}

      <ReduxProvider>
        <body className={outfit.className}>
        {/* <ToastProvider> */}
          {/* <div>
            <Toaster />
          </div> */}
          {children}
          {/* </ToastProvider> */}
        </body>
      </ReduxProvider>
    </html>
  );
}
